apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-dte-conf
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets: null
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090
      - job_name: kube-state-metrics
        static_configs:
          - targets:
              - kube-state-metrics.kube-system.svc.cluster.local:8080
      - job_name: cadvisor
        scrape_interval: 15s
        scrape_timeout: 15s
        scheme: http
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_container_name
            regex: cadvisor
            action: keep
          - source_labels:
              - __address__
              - __meta_kubernetes_pod_container_port_name
              - __meta_kubernetes_namespace
            separator: ;
            regex: (.+);cadvisor;(.+)
            target_label: __address__
            replacement: ${1}:${2}
            action: replace
      - job_name: node-exporter
        scrape_interval: 15s
        scrape_timeout: 15s
        scheme: http
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_container_name
            regex: node-exporter
            action: keep
          - source_labels:
              - __address__
              - __meta_kubernetes_pod_container_port_name
              - __meta_kubernetes_namespace
            separator: ;
            regex: (.+);node-exporter;(.+)
            target_label: __address__
            replacement: ${1}:${2}
            action: replace
      - job_name: dte-pe
        honor_timestamps: true
        scrape_interval: 1m
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        follow_redirects: true
        enable_http2: true
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            separator: ;
            regex: "true"
            replacement: $1
            action: keep
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            separator: ;
            regex: (.+)
            target_label: __metrics_path__
            replacement: $1
            action: replace
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            separator: ;
            regex: ([^:]+)(?::\d+)?;(\d+)
            target_label: __address__
            replacement: $1:$2
            action: replace
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
            separator: ;
            regex: (https?)
            target_label: __scheme__
            replacement: $1
            action: replace
          - source_labels: [__meta_kubernetes_namespace]
            separator: ;
            regex: (.*)
            target_label: kubernetes_namespace
            replacement: $1
            action: replace
          - source_labels: [__meta_kubernetes_pod_name]
            separator: ;
            regex: (.*)
            target_label: kubernetes_pod_name
            replacement: $1
            action: replace
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - dte-prod-pe
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-gp3-claim
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-dte
  name: prometheus-dte
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-dte
  template:
    metadata:
      labels:
        app: prometheus-dte
    spec:
      initContainers:
      - name: create-subdir-take-data-dir-ownership
        image: alpine:3
        command: ["/bin/sh", "-c"]
        args: ["chmod 777 /prometheus"]
        volumeMounts:
        - mountPath: /prometheus
          name: storage
          subPathExpr: prometheus
      containers:
      - name: prometheus-dte
        image: prom/prometheus:v2.43.0
        args:
          - --config.file=/etc/prometheus/prometheus.yml
          - --web.external-url=https://crmsubsysbgg.dialog.lk/prometheus-dte
          - --web.route-prefix=/
        ports:
        - containerPort: 9090
          protocol: TCP
        resources:
          limits:
            cpu: 600m
            memory: 9000Mi
          requests:
            cpu: 500m
            memory: 8000Mi
        volumeMounts:
        - mountPath: /etc/prometheus
          name: prometheus-dte-conf
          readOnly: true
        - mountPath: /prometheus
          name: storage
          subPathExpr: prometheus
      volumes:
      - name: prometheus-dte-conf
        configMap:
          name: prometheus-dte-conf
      - name: storage
        persistentVolumeClaim:
          claimName: ebs-gp3-claim
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-dte
  namespace: monitoring
spec:
  selector:
    app: prometheus-dte
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
